---
title: "Milestone #2"
author: "Olly Gill"
date: "September 17, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Project 1: Harvard Blocking Project
One of the things that I found so interesting about this project is the obvious fact that it relates to the audience to which it is being presented to. Every undergraduate student in the class obviously went through this process so I think it is a great pro to this project because it engages everyone who is looking at it. Once you open the project, I think one of the major pros is that there are many different categories that break down the blocking topic. The creator, Dasha, did a really good job of having not only basic questions like "Where are linking groups placed?" but also more intricate questions that dive into the blocking process like "What is the race and gender breakdown by location?" Each of the questions has a really tidy graph that gives a visual illustration of the data collected. I think the extensiveness of the different graphs created is definitely the biggest pro of the project because it shows that the creator was not just interested in one or two questions but really wanted to show that their data is covering a wide array of details that relate to their project. However, one related con of the project is that the data was only collected for 50.2% of the class so that also means that there is a vast amount of data missing which could lead to the data collected to be a bit skewed. I also think that since the data was just collected from one graduating class it makes it hard to advertise the project as Harvard blocking in general when instead it should have been just for one class as a glimpse into the process as a whole. I think that it would have been a pro if the project was able to have data from different grades and then you were able to sort the data by grade. Overall the project was incredibly interesting and I really enjoyed being able to spend time looking at the graphs and responses.

Project 2: Course Enrollment Analysis
I was drawn to this project because, like the other project I looked into, it is something that I relate to and am involved in. Being a student I am curious to see what kinds of courses people enjoy taking. I also know that after reading the "about" tab of the project that the data is covering an incredibly vast amount of people as the creator, Chris, was able to use a public dataset from the Harvard Register. This is a major pro of the project because it means that the information gathered is from a wide array of data points and not a small subset of the population. One of the things I thought was executed very well in this project was that it was able to include data about enrollment from an overview in departments over the years and then was able to dive into semesters and particular courses in the different departments. I think it is a major benefit of this project to have data available on the broad scale as well as on a much smaller level with individual courses. I also thought it was smart of the Chris to use different kinds of graphs in the project and not all only one type. For example, I liked that there were line graphs as well as histograms and point plots. One of the things I think was a bit of a con from the project is that while it did include specifics regarding the largest enrollment in particular classes in each of the departments, I wish there was more data on individual classes that you could sort through. I would have liked the data to be a bit more specific in some of the distribution of classes and not just information on which is the largest. I think the biggest con of this project is that those looking into it want more information and more detail. However, overall I really enjoyed being able to look around in this project.